INSERT INTO voucher_type (id, name, config, is_default, auto_sequence, base_type, created_by, updated_by, created_at, updated_at, changed_at)
VALUES
    (1, 'Payment', '{"payment":{"print_after_save":false,"enable_silent_print_mode":false,"pos_counter_transaction_only":false,"enable_single_entry_mode":true}}', true, true, 'PAYMENT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (2, 'Receipt', '{"receipt":{"print_after_save":false,"enable_silent_print_mode":false,"pos_counter_transaction_only":false,"enable_single_entry_mode":true}}', true, true, 'RECEIPT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (3, 'Contra', '{"contra":{"print_after_save":false,"enable_silent_print_mode":false,"enable_single_entry_mode":true}}', true, true, 'CONTRA', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (4, 'Journal', '{"journal":{"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'JOURNAL', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (5, 'Sale', '{"sale":{"enable_e_invoice":false,"account":{"print_after_save":false,"enable_single_entry_mode":false,"allowed_bill_ref_types":["NEW","ADJ","ON_ACC"]},"inventory":{"pos_counter_transaction_only":false,"warehouse_enabled":false,"hide_rack":false,"hide_mrp_in_batch_modal":false,"rate_editable":false,"tax_editable":false,"discount_editable":false,"unit_editable":false,"bill_discount_editable":false,"print_after_save":false,"auto_select_batch":false,"set_default_qty":false,"enable_silent_print_mode":false,"enable_reminder_days":false,"enable_description":true,"enable_doctor":false,"allow_credit_customer":false,"enable_sales_person":false,"voucherwise_sales_person":false,"freeze_sales_person_for_voucher":false,"barcode_enabled":false,"customer_form_quick_create":false,"enable_exchange":false,"enable_advance":false,"enable_emi":false,"price_list_editable":false,"default_price_list":null,"set_retail_qty":false,"set_focus_on_inventory":false,"primary_payment_modes":["CARD"],"allowed_credit_accounts":[],"allowed_emi_accounts":[],"allowed_card_accounts":[]}}}', true, true, 'SALE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (6, 'Credit Note', '{"credit_note":{"account":{"print_after_save":false,"enable_single_entry_mode":false,"allowed_bill_ref_types":["NEW","ADJ","ON_ACC"]},"inventory":{"pos_counter_transaction_only":false,"warehouse_enabled":false,"rate_editable":false,"tax_editable":false,"discount_editable":false,"unit_editable":false,"bill_discount_editable":false,"print_after_save":false,"enable_silent_print_mode":false,"allow_credit_customer":false,"enable_sales_person":false,"voucherwise_sales_person":false,"freeze_sales_person_for_voucher":false,"barcode_enabled":false,"enable_exp":false,"customer_form_quick_create":false,"print_customer_copy":false,"invoice_no_required":false,"is_exchange_voucher":false,"price_list_editable":false,"default_price_list":null,"set_retail_qty":false,"set_focus_on_inventory":false,"customer_required":false}}}', true, true, 'CREDIT_NOTE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (7, 'Purchase', '{"purchase":{"account":{"print_after_save":false,"enable_single_entry_mode":false},"inventory":{"print_after_save":false,"s_rate_mrp_required":false,"s_rate_as_mrp":false,"enable_silent_print_mode":false,"allow_credit_vendor":true,"barcode_enabled":false,"prevent_loss":false,"tax_hide":false,"enable_gin":false,"enable_expiry":false,"expiry_required":false,"is_exchange_voucher":false,"enable_bill_detail":true,"enable_automatic_rounded_off":false,"enable_weight_bill":false,"allow_new_ref_only":false,"bill_format":"NORMAL","set_retail_qty":false,"set_focus_on_inventory":false,"exchange_customer_required":false,"bill_copy_required":false,"gate_entry_required":false}}}', true, true, 'PURCHASE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (8, 'Debit Note', '{"debit_note":{"account":{"print_after_save":false,"enable_single_entry_mode":false},"inventory":{"cash_register_enabled":false,"warehouse_enabled":false,"rate_editable":false,"tax_editable":false,"discount_editable":false,"print_after_save":false,"enable_silent_print_mode":false,"allow_credit_vendor":false,"barcode_enabled":false,"enable_exp":false,"bill_no_required":false,"set_retail_qty":false,"set_focus_on_inventory":false}}}', true, true, 'DEBIT_NOTE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (9, 'Sale Quotation', '{"sale_quotation":{"rate_editable":false,"tax_editable":false,"discount_editable":false,"unit_editable":false,"bill_discount_editable":false,"enable_silent_print_mode":false,"print_after_save":false,"barcode_enabled":false,"enable_exp":false,"set_retail_qty":false,"set_focus_on_inventory":false}}', true, true, 'SALE_QUOTATION', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (10, 'Stock Adjustment', '{"stock_adjustment":{"enable_silent_print_mode":false,"print_after_save":false,"barcode_enabled":false,"enable_exp":false,"set_retail_qty":false,"set_focus_on_inventory":false}}', true, true, 'STOCK_ADJUSTMENT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (11, 'Transfer Out', '{"transfer_out":{"enable_silent_print_mode":false,"print_after_save":false,"barcode_enabled":false,"enable_exp":false,"alt_branch_required":false,"set_retail_qty":false,"set_focus_on_inventory":false,"enable_target_branch":true,"enable_target_warehouse":true}}', true, true, 'TRANSFER_OUT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (12, 'Transfer In', '{"transfer_in":{"enable_silent_print_mode":false,"print_after_save":false,"barcode_enabled":false,"enable_exp":false,"alt_branch_required":false,"set_retail_qty":false,"set_focus_on_inventory":false,"import_from_source":true}}', true, true, 'TRANSFER_IN', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (14, 'Manufacturing Journal', '{"manufacturing_journal":{"barcode_enabled":false}}', true, true, 'MANUFACTURING_JOURNAL', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (15, 'Memo', '{"payment":{"memo_only":true,"print_after_save":false,"open_cheque_book_detail":false,"enable_single_entry_mode":true}}', true, true, 'PAYMENT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (16, 'Wastage', '{"wastage":{"enable_silent_print_mode":false,"print_after_save":false,"barcode_enabled":false,"enable_exp":false}}', true, true, 'WASTAGE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (17, 'Goods Inward Note', '{"goods_inward_note":{"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'GOODS_INWARD_NOTE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (19, 'Purchased Goods For Personal Use', '{"personal_use_purchase":{"allowed_expense_accounts":[],"set_retail_qty":false,"set_focus_on_inventory":false}}', true, true, 'PERSONAL_USE_PURCHASE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (20, 'Customer Advance', '{"customer_advance":{"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'CUSTOMER_ADVANCE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (21, 'Delivery Note', '{"delivery_note":{"print_after_save":false,"enable_silent_print_mode":false,"enable_description":false,"shipping_charge_account":18}}', true, true, 'DELIVERY_NOTE', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (22, 'Shipment', '{"shipment":{"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'SHIPMENT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (23, 'Delivery Receipt', '{"delivery_receipt":{"enable_description":false,"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'DELIVERY_RECEIPT', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (24, 'Eft Reconciliation Voucher', '{"eft_reconciliation_voucher":{"enable_description":false,"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'EFT_RECONCILIATION_VOUCHER', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (25, 'Sales Emi Reconciliation Voucher', '{"sales_emi_reconciliation_voucher":{"enable_description":false,"print_after_save":false,"enable_silent_print_mode":false}}', true, true, 'SALES_EMI_RECONCILIATION_VOUCHER', 1, 1, current_timestamp, current_timestamp, current_timestamp),
    (26, 'Expense', '{"payment":{"print_after_save":false,"enable_silent_print_mode":false,"pos_counter_transaction_only":false,"enable_single_entry_mode":true}}', true, true, 'PAYMENT', 1, 1, current_timestamp, current_timestamp, current_timestamp);
--##
SELECT setval('voucher_type_id_seq', 100);
--##