insert into country (id, name, country_id, changed_at)
values ('INDIA', 'India', null, current_timestamp),
       ('01', 'Jammu and Kashmir', 'INDIA', current_timestamp),
       ('02', 'Himachal Pradesh', 'INDIA', current_timestamp),
       ('03', 'Punjab', 'INDIA', current_timestamp),
       ('04', 'Chandigarh', 'INDIA', current_timestamp),
       ('05', 'Uttarakhand', 'INDIA', current_timestamp),
       ('06', 'Haryana', 'INDIA', current_timestamp),
       ('07', 'Delhi', 'INDIA', current_timestamp),
       ('08', 'Rajasthan', 'INDIA', current_timestamp),
       ('09', 'Uttar Pradesh', 'INDIA', current_timestamp),
       ('10', 'Bihar', 'INDIA', current_timestamp),
       ('11', 'Sikkim', 'INDIA', current_timestamp),
       ('12', 'Arunachal Pradesh', 'INDIA', current_timestamp),
       ('13', 'Nagaland', 'INDIA', current_timestamp),
       ('14', 'Manipur', 'INDIA', current_timestamp),
       ('15', 'Mizoram', 'INDIA', current_timestamp),
       ('16', 'Tripura', 'INDIA', current_timestamp),
       ('17', 'Meghalaya', 'INDIA', current_timestamp),
       ('18', 'Assam', 'INDIA', current_timestamp),
       ('19', 'West Bengal', 'INDIA', current_timestamp),
       ('20', 'Jharkhand', 'INDIA', current_timestamp),
       ('21', 'Odisha', 'INDIA', current_timestamp),
       ('22', 'Chhattisgarh', 'INDIA', current_timestamp),
       ('23', 'Madhya Pradesh', 'INDIA', current_timestamp),
       ('24', 'Gujarat', 'INDIA', current_timestamp),
       ('25', 'Daman and Diu', 'INDIA', current_timestamp),
       ('26', 'Dadra and Nagar Haveli and Daman and Diu', 'INDIA', current_timestamp),
       ('27', 'Maharashtra', 'INDIA', current_timestamp),
       ('29', 'Karnataka', 'INDIA', current_timestamp),
       ('30', 'Goa', 'INDIA', current_timestamp),
       ('31', 'Lakshadweep', 'INDIA', current_timestamp),
       ('32', 'Kerala', 'INDIA', current_timestamp),
       ('33', 'Tamil Nadu', 'INDIA', current_timestamp),
       ('34', 'Pondicherry', 'INDIA', current_timestamp),
       ('35', 'Andaman and Nicobar Islands', 'INDIA', current_timestamp),
       ('36', 'Telangana', 'INDIA', current_timestamp),
       ('37', 'Andhra Pradesh', 'INDIA', current_timestamp),
       ('38', 'Ladakh', 'INDIA', current_timestamp),
       ('97', 'Other Territory', 'INDIA', current_timestamp);