select * from section; --✅
select * from bank; --✅
select * from bank_beneficiary; --✅
select * from uqc; --✅
select * from gst_tax; --✅
select * from account_type; --✅
select * from tds_nature_of_payment; --✅
select * from account; --✅
select * from country; --✅
select * from branch; --✅
select * from gst_registration; --✅
select * from warehouse; --✅
select * from organization; --✅
select * from voucher_type; --✅
select * from member; --✅
select * from financial_year; --✅
select * from unit; --✅
select * from stock_location; --✅
select * from manufacturer; --✅
select * from bill_of_material; --✅
select * from inventory; --✅
select * from inventory_branch_detail; --✅
select * from permission; --✅
select * from hsn_code; --✅
select * from voucher_numbering; --✅
select * from voucher; --✅
select * from ac_txn; --✅
select * from account_daily_summary; --✅
select * from bill_allocation; --✅
select * from bank_txn; --✅
select * from tds_on_voucher; --✅
select * from batch; --✅
select * from inv_txn; --✅

